insert into "countries" ("country", "currency")

values ('AFGHANISTAN', 'AFN'),
      ('ALBANIA', 'ALL'),
      ('ALGERIA', 'DZD'),
      ('ANDORRA', 'EUR'),
      ('ANGOLA', 'AOA'),
      ('ANGUILLA', 'XCD'),
      ('ANTIGUA AND BARBUDA', 'XCD'),
      ('ARGENTINA', 'ARS'),
      ('ARMENIA', 'AMD'),
      ('ARUBA', 'AWG'),
      ('AUSTRALIA', 'AUD'),
      ('AUSTRIA', 'EUR'),
      ('AZERBAIJAN', 'AZN'),
      ('BAHAMAS', 'BSD'),
      ('BAHRAIN', 'BHD'),
      ('BANGLADESH', 'BDT'),
      ('BARBADOS', 'BBD'),
      ('BELARUS', 'BYN'),
      ('BELGIUM', 'EUR'),
      ('BELIZE', 'BZD'),
      ('BENIN', 'XOF'),
      ('BERMUDA', 'BMD'),
      ('BHUTAN', 'BTN'),
      ('BOLIVIA', 'BOB'),
      ('BOSNIA AND HERZEGOVINA', 'BAM'),
      ('BOTSWANA', 'BWP'),
      ('BOUVET ISLAND', 'NOK'),
      ('BRAZIL', 'BRL'),
      ('BULGARIA', 'BGN'),
      ('BURKINA FASO', 'XOF'),
      ('BURUNDI', 'BIF'),
      ('CABO VERDE', 'CVE'),
      ('CAMBODIA', 'KHR'),
      ('CAMEROON', 'XAF'),
      ('CANADA', 'CAD'),
      ('CAYMAN ISLANDS', 'KYD'),
      ('CENTRAL AFRICAN REPUBLIC', 'XAF'),
      ('CHAD', 'XAF'),
      ('CHILE', 'CLF'),
      ('CHINA', 'CNY'),
      ('CHRISTMAS ISLAND', 'AUD'),
      ('COCOS ISLANDS', 'AUD'),
      ('COLOMBIA', 'COP'),
      ('COMOROS', 'KMF'),
      ('CONGO', 'CDF'),
      ('COOK ISLANDS', 'NZD'),
      ('COSTA RICA', 'CRC'),
      ('CROATIA', 'HRK'),
      ('CUBA', 'CUP'),
      ('CURAÇAO', 'ANG'),
      ('CYPRUS', 'EUR'),
      ('CZECH REPUBLIC', 'CZK'),
      ('CÔTE D IVOIRE', 'XOF'),
      ('DENMARK', 'DKK'),
      ('DJIBOUTI', 'DJF'),
      ('DOMINICA', 'XCD'),
      ('DOMINICAN REPUBLIC', 'DOP'),
      ('ECUADOR', null),
      ('EGYPT', 'EGP'),
      ('EL SALVADOR', 'SVC'),
      ('EQUATORIAL GUINEA', 'XAF'),
      ('ERITREA', 'ERN'),
      ('ESTONIA', 'EUR'),
      ('ETHIOPIA', 'ETB'),
      ('EUROPEAN UNION', 'EUR'),
      ('FALKLAND ISLANDS', 'FKP'),
      ('FAROE ISLANDS', 'DKK'),
      ('FIJI', 'FJD'),
      ('FINLAND', 'EUR'),
      ('FRANCE', 'EUR'),
      ('FRENCH GUIANA', 'EUR'),
      ('FRENCH POLYNESIA', 'XPF'),
      ('GABON', 'XAF'),
      ('GAMBIA', 'GMD'),
      ('GEORGIA', 'GEL'),
      ('GERMANY', 'EUR'),
      ('GHANA	Ghana', 'GHS'),
      ('GIBRALTAR', 'GIP'),
      ('GREECE', 'EUR'),
      ('GREENLAND', 'DKK'),
      ('GRENADA', 'XCD'),
      ('GUADELOUPE', 'EUR'),
      ('GUAM', null),
      ('GUATEMALA', 'GTQ'),
      ('GUERNSEY', 'GBP'),
      ('GUINEA', 'GNF'),
      ('GUYANA', 'GYD'),
      ('HAITI', 'HTG'),
      ('HONDURAS', 'HNL'),
      ('HONG KONG', 'HKD'),
      ('HUNGARY', 'HUF'),
      ('ICELAND', 'ISK'),
      ('INDIA', 'INR'),
      ('INDONESIA', 'IDR'),
      ('IRAN', 'IRR'),
      ('IRAQ', 'IQD'),
      ('IRELAND', 'EUR'),
      ('ISLE OF MAN', 'GBP'),
      ('ISRAEL', 'ILS'),
      ('ITALY', 'EUR'),
      ('JAMAICA', 'JMD'),
      ('JAPAN', 'JPY'),
      ('JERSEY', 'GBP'),
      ('JORDAN', 'JOD'),
      ('KAZAKHSTAN', 'KZT'),
      ('KENYA', 'KES'),
      ('KIRIBATI', 'AUD'),
      ('KOREA', 'KRW'),
      ('KUWAIT', 'KWD'),
      ('KYRGYZSTAN', 'KGS'),
      ('LATVIA', 'EUR'),
      ('LEBANON', 'LBP'),
      ('LESOTHO', 'LSL'),
      ('LIBYA', 'LYD'),
      ('LIECHTENSTEIN', 'CHF'),
      ('LITHUANIA', 'EUR'),
      ('LUXEMBOURG', 'EUR'),
      ('MACAO', 'MOP'),
      ('MADAGASCAR', 'MGA'),
      ('MALAWI', 'MWK'),
      ('MALAYSIA', 'MYR'),
      ('MALDIVES', 'MVR'),
      ('MALI', 'XOF'),
      ('MALTA', 'EUR'),
      ('MARSHALL ISLANDS', null),
      ('MARTINIQUE', 'EUR'),
      ('MAURITANIA', 'MRU'),
      ('MAURITIUS', 'MUR'),
      ('MAYOTTE', 'EUR'),
      ('MEXICO', 'MXN'),
      ('MICRONESIA', null),
      ('MOLDOVA', 'MDL'),
      ('MONACO', 'EUR'),
      ('MONGOLIA', 'MNT'),
      ('MONTENEGRO', 'EUR'),
      ('MONTSERRAT', 'XCD'),
      ('MOROCCO', 'MAD'),
      ('MOZAMBIQUE', 'MZN'),
      ('MYANMAR', 'MMK'),
      ('NAMIBIA', 'NAD'),
      ('NAURU', 'AUD'),
      ('NEPAL', 'NPR'),
      ('NETHERLANDS', 'EUR'),
      ('NEW CALEDONIA', 'XPF'),
      ('NEW ZEALAND', 'NZD'),
      ('NICARAGUA', 'NIO'),
      ('NIGER', 'XOF'),
      ('NIGERIA', 'NGN'),
      ('NIUE', 'NZD'),
      ('NORFOLK ISLAND', 'AUD'),
      ('NORTHERN MARIANA ISLANDS', null),
      ('NORWAY', 'NOK'),
      ('OMAN', 'OMR'),
      ('PAKISTAN', 'PKR'),
      ('PALAU', null),
      ('PANAMA', 'PAB'),
      ('PAPUA NEW GUINEA', 'PGK'),
      ('PARAGUAY', 'PYG'),
      ('PERU', 'PEN'),
      ('PHILIPPINES', 'PHP'),
      ('PITCAIRN', 'NZD'),
      ('POLAND', 'PLN'),
      ('PORTUGAL', 'EUR'),
      ('PUERTO RICO', null),
      ('QATAR', 'QAR'),
      ('REPUBLIC OF NORTH MACEDONIA', 'MKD'),
      ('ROMANIA', 'RON'),
      ('RUSSIA', 'RUB'),
      ('RWANDA', 'RWF'),
      ('RÉUNION', 'EUR'),
      ('SAINT BARTHÉLEMY', 'EUR'),
      ('SAINT KITTS', 'XCD'),
      ('SAINT LUCIA', 'XCD'),
      ('SAINT MARTIN', 'EUR'),
      ('SAINT PIERRE', 'EUR'),
      ('SAMOA', 'WST'),
      ('SAN MARINO', 'EUR'),
      ('SAO TOME AND PRINCIPE', 'STN'),
      ('SAUDI ARABIA', 'SAR'),
      ('SENEGAL', 'XOF'),
      ('SERBIA', 'RSD'),
      ('SEYCHELLES', 'SCR'),
      ('SIERRA LEONE', 'SLL'),
      ('SINGAPORE', 'SGD'),
      ('SLOVAKIA', 'EUR'),
      ('SLOVENIA', 'EUR'),
      ('SOLOMON ISLANDS', 'SBD'),
      ('SOMALIA', 'SOS'),
      ('SOUTH AFRICA', 'ZAR'),
      ('SOUTH SUDAN', 'SSP'),
      ('SPAIN', 'EUR'),
      ('SRI LANKA', 'LKR'),
      ('SUDAN', 'SDG'),
      ('SURINAME', 'SRD'),
      ('SWAZILAND', 'SZL'),
      ('SWEDEN', 'SEK'),
      ('SWITZERLAND', 'CHF'),
      ('SYRIAN ARAB REPUBLIC', 'SYP'),
      ('TAIWAN', 'TWD'),
      ('TAJIKISTAN', 'TJS'),
      ('TANZANIA', 'TZS'),
      ('THAILAND', 'THB'),
      ('TIMOR-LESTE', null),
      ('TOGO', 'XOF'),
      ('TOKELAU', 'NZD'),
      ('TONGA', 'TOP'),
      ('TRINIDAD AND TOBAGO', 'TTD'),
      ('TUNISIA', 'TND'),
      ('TURKEY', 'TRY'),
      ('TURKMENISTAN', 'TMT'),
      ('TURKS AND CAICOS', null),
      ('TUVALU', 'AUD'),
      ('UGANDA', 'UGX'),
      ('UKRAINE', 'UAH'),
      ('UNITED ARAB EMIRATES', 'AED'),
      ('UNITED KINGDOM', 'GBP'),
      ('URUGUAY', 'UYI'),
      ('UZBEKISTAN', 'UZS'),
      ('VANUATU', 'VUV'),
      ('VENEZUELA', 'VEF'),
      ('VIET NAM', 'VND'),
      ('VIRGIN ISLANDS', null),
      ('WALLIS', 'XPF'),
      ('WESTERN SAHARA', 'MAD'),
      ('YEMEN', 'YER'),
      ('ZAMBIA', 'ZMW'),
      ('ZIMBABWE', 'ZWL')
returning *;
